import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import { Inter, Poppins, Roboto, Montserrat, Raleway } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins'
});
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto'
});
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
});
const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`
                ${inter.variable} 
                ${poppins.variable} 
                ${roboto.variable} 
                ${montserrat.variable} 
                ${raleway.variable}
            `}>
        <NextTopLoader height={5} />
        {children}
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#fff',
              color: '#333',
              padding: '16px',
              borderRadius: '8px',
              boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
              fontSize: '14px',
              maxWidth: '400px',
              border: '1px solid #e2e8f0',
            },
            success: {
              style: {
                backgroundColor: '#f8fafc',
                border: '1px solid #22c55e',
              },
              iconTheme: {
                primary: '#22c55e',
                secondary: '#ffffff',
              },
            },
            error: {
              style: {
                backgroundColor: '#f8fafc',
                border: '1px solid #ef4444',
              },
              iconTheme: {
                primary: '#ef4444',
                secondary: '#ffffff',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
